---
#tasks for install AD
- name: Debug
  debug:
    msg: "{{ ad_admin_user }}"

- name: Install AD-Domain-Services
  win_feature:
   name: AD-Domain-Services
   state: present
  register: win_feature
## resgister the win_feature variable to check later if the reboot is required

- name: Set up AD controller
  win_domain:
    dns_domain_name:  "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}" 

- name: Print out the domain
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: domain_list

- name: Print debug
  debug:
    var: domain_list
    
#- name: Create Admin user
#  win_user:
#    name: "{{ ad_admin_user }}"
#    password: "{{ ad_admin_password }}"
##   state: present
- name: Reboot if required
  win_reboot:
  when: win_feature.reboot_required
