---
#tasks for install SSH
- name: 
  debug:
    msg: "{{ ansible_distribution }}"
   
- name: InstallSSH
  win_chocolatey:
    name: "{{ package_name }}" 
    package_params: "{{ parameters }}" 
    state: present 
  when: (ansible_distribution == "Microsoft Windows Server 2012 R2 Standard")

- name: Start SSH
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto

- name: Add win_firewall_rule
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
